version: '3'

services:
  # NoSQL Database
  mongo:
    image: bitnami/mongodb:6.0
    restart: always
    environment:
      - MONGODB_ROOT_PASSWORD=sicp_root
      - MONGODB_USERNAME=sicp
      - MONGODB_PASSWORD=sicp
      - MONGODB_DATABASE=sicp
    volumes:
      - ./data/mongo:/bitnami/mongodb
    ports:
      - "127.0.0.1:23001:27017"
  
  # Object Storage
  minio:
    image: bitnami/minio:2022
    restart: always
    environment:
      - MINIO_ROOT_USER=sicp_minio
      - MINIO_ROOT_PASSWORD=sicp_minio
      - MINIO_DEFAULT_BUCKETS=sicp
    volumes:
      - ./data/minio:/data
    ports:
      - "127.0.0.1:23002:9000"
      - "127.0.0.1:23003:9001"

  # Message broker
  rabbitmq:
    image: bitnami/rabbitmq:3.10
    restart: always
    environment:
      - RABBITMQ_USERNAME=sicp
      - RABBITMQ_PASSWORD=sicp
    volumes:
      - ./data/rabbitmq:/bitnami
    ports:
      - "127.0.0.1:23004:5672"
      - "127.0.0.1:23005:15672"

  # In-memory cache
  redis:
    image: bitnami/redis:7.0
    restart: always
    environment:
      - REDIS_PASSWORD=sicp
    volumes:
      - ./data/redis:/bitnami/redis/data
    ports:
      - "127.0.0.1:23006:6379"
  
  # Docker registry
  # To restrict access to registry, refer to
  # https://docs.docker.com/registry/deploying/#restricting-access
  registry:
    image: registry:2
    restart: always
    volumes:
      - ./data/registry:/var/lib/registry
    ports:
      - "127.0.0.1:23009:5000"
