sicp:
  admin:
    username: admin
    password: password
    fullName: 系统管理员
  jwt:
    issuer: sicp
    audience: sicp-user
    secret: dsfghjfsghjkdfghkjldfsjhfl34958029084390849
  oauth2:
    gitlab:
      endpoint: https://git.nju.edu.cn
      clientId: 1
      clientSecret: 1
      redirectUri: 1
      scope: 1
  docker:
    host: tcp://172.16.70.2:2375
    tls-verify: false
    #tls-cert-path:
    registry-url: http://172.16.70.2:5000
    #registry-email:
    #registry-username:
    #registry-password:
  s3:
    endpoint: http://172.16.70.2:9000
    access-key: sicp_minio
    secret-key: sicp_minio
    region: us-east-1
    bucket: sicp

spring:
  application:
    name: SICP Online Judge
  data:
    mongodb:
      host: 172.16.70.2
      port: 27017
      database: sicp
      username: mongo
      password: mongo
  rabbitmq:
    host: 172.16.70.2
    port: 5672
    username: rabbitmq
    password: rabbitmq
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

logging:
  file:
    name: sicp.log
  level:
    root: ERROR
    cn.edu.nju.sicp: INFO
  logback:
    rollingpolicy:
      max-history: 365

server:
  port: 8080
  error:
    include-message: always
    whitelabel:
      enabled: false
